title: My Minimal Mistakes Site
description: >- # this means to ignore newlines until "baseurl:"
  A clean, modern Jekyll theme for building a personal site, blog, project showcase, or portfolio.
baseurl: "" # Leave empty for GitHub Pages root
url: "https://nbourre.github.io" # Update to your GitHub Pages URL
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
